steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/samus-486501/servicosimples/veterinaria', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/samus-486501/servicosimples/veterinaria']
images:
  - 'us-central1-docker.pkg.dev/samus-486501/servicosimples/veterinaria'
